### ISSUE TITLE
Some basic issues！Thanks！

### ISSUE THREAD

**Issue by 1334233852** [hkchengrex/vos-benchmark#1]
Hello author, thank you very much for your outstanding contribution!But I have a few basic questions that I would like to consult with you，My predicted mask folder layout and my own dataset layout are shown in the following figure
![文件夹布局](https://github.com/hkchengrex/vos-benchmark/assets/118711216/93033c30-9d3c-464b-8bed-11a1273fa257)
When I use the following command line, there will be a basic error
![命令](https://github.com/hkchengrex/vos-benchmark/assets/118711216/232c0f97-344b-4bc6-a140-53edc6798257)
![报错信息](https://github.com/hkchengrex/vos-benchmark/assets/118711216/09af0293-eab1-4440-90e3-97c61c987ece)
When I use the following command line, there will be a basic error

**Comment by 1334233852** [comment]
Excuse me again! Another issue, which caused me to use the absolute path to not display the above issue, resulted in the following issue.
![问题](https://github.com/hkchengrex/vos-benchmark/assets/118711216/9a541375-9580-4b19-807d-2e7c116f5f7c)
很抱歉，我是一个菜鸟新手，可能问的问题很基础！打扰了

**Comment by hkchengrex** [comment]
1. Relative paths should work. Are you sure that the paths are pointing to the correct directory?
2. Might happen if the code cannot find a single video in the path that you provided.

**Comment by 1334233852** [comment]
Thank you very much for your reply! There are still some issues with relative paths. I have temporarily used absolute paths and made some changes, which have been effective! thanks
