### ISSUE TITLE
A description of the output results

### ISSUE THREAD

**Issue by Air1000thsummer** [hkchengrex/vos-benchmark#5]
Rex Hello!
I would like to ask you if there are two results for each video in the output result, is this because the J&F value of both targets in this video has been calculated?

![Uploading G487STM(SZ$RJP`]K2B@X~C.png…]()

**Comment by Air1000thsummer** [comment]
![G487STM(SZ$RJP` K2B@X~C](https://github.com/hkchengrex/vos-benchmark/assets/138500800/36516699-16dc-4887-b502-068b37dd714e)

**Comment by hkchengrex** [comment]
Yes. 001 is for the first object and so on.

**Comment by Air1000thsummer** [comment]
thanks!
